### ISSUE TITLE
[Feat] 인정, 부정 로직 구현

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2024-OUTFOOT-Server#20]
## 📌 Issue

인증판 인정, 부정 로직 구현

---

## 📌 TODO
* [x] 인정 로직 구현
* [x] 부정 로직 구현
* [x] 중복 로직 예외 터트리기 (인정, 부정 동시에 누르기 X)
* [x] 다시 누르면 인정 및 부정 취소 로직 작성
* [x] 추후에 find 로직 구현할 때 dto로 감싸주기 -> dto에서 entity로 변환하는 로직 필요
