### ISSUE TITLE
[Feat] 친구 프로필 조회 시 이미지 전달

### ISSUE THREAD

**Issue by gustj3104** [APPS-sookmyung/2024-OUTFOOT-Server#73]
## 📌 Issue

친구 프로필 조회 시 이미지 전달 로직 구현
---

## 📌 TODO
* [ ] Friend 객체에 이미지 URL 추가
* [ ] null 이미지 처리
* [ ] FriendList에 이미지 URL 추가
