### ISSUE TITLE
[Feat] 칭찬판 관리 로직 구현

### ISSUE THREAD

**Issue by ajung7038** [APPS-sookmyung/2024-OUTFOOT-Server#9]
## 📌 Issue

칭찬판 CRUD 구현

---

## 📌 TODO
* [x] 칭찬판 추가
* [x] Animal type (String) -> Animal
* [x] 예외 처리 로직 구현
* [x] 칭찬판 개별 조회
* [x] 칭찬판 전체 조회
* [x] 칭찬판 삭제
